/**
 * Core-internal shared types.
 *
 * These types are used across the core package but are not part of the public
 * API surface. Public-facing shapes come from packages/protocol.
 */

import type { ModelToolCall } from "@agent-workbench/models";

/**
 * Provider-neutral message representation used within the context builder and
 * model router. Mirrors the model-message concept without being tied to any
 * specific wire format.
 */
export interface ContextMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  /**
   * Present when role === "tool" — correlates the result with the model's
   * original tool-call ID.
   */
  toolCallId?: string;
  /**
   * Present when role === "assistant" and the model requested tool calls.
   * Used by provider adapters to reconstruct assistant tool-call turns.
   */
  toolCalls?: readonly ModelToolCall[];
}

/**
 * A parsed tool-call request as extracted from a model response and enriched
 * with a storage-level ID for tracking.
 */
export interface ToolCallRequest {
  /** ULID generated by core for storage / ledger tracking. */
  id: string;
  /** Provider-generated call ID (used in the tool-result message). */
  modelCallId: string;
  name: string;
  input: unknown;
}

/** Result of a dispatched tool call returned to the model/tool loop. */
export interface ToolCallResult {
  /** Correlates with ToolCallRequest.id. */
  id: string;
  /** Correlates with ToolCallRequest.modelCallId. */
  modelCallId: string;
  name: string;
  /** Serialisable result to embed in the model conversation. */
  result: unknown;
  /** Present when the tool call failed or the tool was not found. */
  error?: string;
}

/** Options accepted by SessionRunner.run(). */
export interface RunOptions {
  /** Caller-supplied abort signal. */
  signal?: AbortSignal;
  /** Override the default system prompt for this run. */
  systemPrompt?: string;
  /** Maximum model/tool loop iterations before the run is aborted. Default 20. */
  maxIterations?: number;
  /**
   * Override the active agent for this run.
   * When undefined, falls back to session.activeAgent then "build".
   */
  agentId?: string;
  /** Maximum run duration in milliseconds before auto-abort. Default 600000 (10 min). */
  maxDurationMs?: number;
}

/** Return value of a completed (or aborted) run. */
export interface RunResult {
  runId: string;
  /** ID of the persisted assistant message. Only present when the run reached a text response. */
  assistantMessageId?: string | undefined;
  status: "completed" | "aborted" | "failed";
  error?: string | undefined;
}

/**
 * All repository/service dependencies injected into the core runtime.
 *
 * Using a dependency-injection object keeps the constructors testable and
 * avoids importing a global storage connection inside core.
 */
export interface CoreDependencies {
  sessionRepository: import("@agent-workbench/storage").SessionRepository;
  messageRepository: import("@agent-workbench/storage").MessageRepository;
  toolCallRepository: import("@agent-workbench/storage").ToolCallRepository;
  ledgerRepository: import("@agent-workbench/storage").LedgerRepository;
  // Phase 8: permission persistence
  permissionRepository: import("@agent-workbench/storage").PermissionRepository;
  // Phase 12: summary persistence and token health
  summaryRepository: import("@agent-workbench/storage").SummaryRepository;
  eventBus: import("@agent-workbench/events").EventBus;
  toolRegistry: import("@agent-workbench/tools").ToolRegistry;
  modelProvider: import("@agent-workbench/models").ModelProvider;
  // Phase 8: permission evaluation and ask-gate
  permissionEngine: import("@agent-workbench/permissions").PermissionEngine;
  permissionGate: import("@agent-workbench/permissions").PermissionGate;
  // Phase 10: shell command runner
  shellRunner: import("@agent-workbench/shell").SimpleCommandRunner;
  // Phase 11: agent registry
  agentRegistry: import("./agent").AgentRegistry;
  // Phase 12: token health
  tokenHealthService: import("./token-health").TokenHealthService;
  // Phase 13: plan persistence and plan gate
  planRepository: import("@agent-workbench/storage").PlanRepository;
  fileChangeRepository: import("@agent-workbench/storage").FileChangeRepository;
}

/** Converts a ModelToolCall (from models package) to a ToolCallRequest. */
export function modelToolCallToRequest(
  call: ModelToolCall,
  storageId: string
): ToolCallRequest {
  return {
    id: storageId,
    modelCallId: call.id,
    name: call.name,
    input: call.input,
  };
}
